# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohlcv',
            name='market_type',
        ),
        migrations.RemoveField(
            model_name='ohlcv',
            name='name',
        ),
    ]
