# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('size_type', models.CharField(blank=True, choices=[('L', 'Large Cap'), ('M', 'Middle Cap'), ('S', 'Small Cap')], max_length=1, null=True)),
                ('style_type', models.CharField(blank=True, choices=[('G', 'Growth'), ('V', 'Value'), ('D', 'Dividend')], max_length=1, null=True)),
                ('market_type', models.CharField(max_length=10)),
                ('face_val', models.IntegerField(blank=True, null=True)),
                ('stock_nums', models.BigIntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('market_cap_rank', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('foreign_limit', models.BigIntegerField(blank=True, null=True)),
                ('foreign_possession', models.BigIntegerField(blank=True, null=True)),
                ('foreign_ratio', models.FloatField(blank=True, null=True)),
                ('per', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('pbr', models.FloatField(blank=True, null=True)),
                ('bps', models.FloatField(blank=True)),
                ('industry_per', models.FloatField(blank=True)),
                ('yield_ret', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
