from django.conf.urls import url
from stockapi.views import (
    BMAPIView,
    CandleAPIView,
    TickerAPIView,
    TickerUpdatedAPIView,
    OHLCVAPIView,
    KospiOHLCVAPIView,
    KosdaqOHLCVAPIView,
    StockInfoAPIView,
    SpecsAPIView,
    InfoAPIView,
    FinancialAPIView,
    FinancialRatioAPIView,
    QuarterFinancialAPIView,
    DailyBuySellAPIView,
    WeeklyBuySellSerializer,

    KospiWeeklyBuyAPIView,
    KosdaqWeeklyBuyAPIView,
    KospiWeeklySellAPIView,
    KosdaqWeeklySellAPIView,
    KospiWeeklyNetAPIView,
    KosdaqWeeklyNetAPIView,
)

urlpatterns = [
    url(r'^bm/$', BMAPIView.as_view(), name='bm'),
    url(r'^ticker/$', TickerAPIView.as_view(), name='ticker'),
    url(r'^ticker-updated/$', TickerUpdatedAPIView.as_view(), name='ticker-updated'),
    url(r'^stockinfo/$', StockInfoAPIView.as_view(), name='stockinfo'),
    url(r'^specs/$', SpecsAPIView.as_view(), name='specs'),
    url(r'^ohlcv/$', OHLCVAPIView.as_view(), name='ohlcv-data'),
    url(r'^kospi/$', KospiOHLCVAPIView.as_view(), name='kospi-ohlcv-data'),
    url(r'^kosdaq/$', KosdaqOHLCVAPIView.as_view(), name='kosdaq-ohlcv-data'),
    url(r'^candle/$', CandleAPIView.as_view(), name='candle'),
    url(r'^info/$', InfoAPIView.as_view(), name='info'),
    url(r'^financial/$', FinancialAPIView.as_view(), name='financial'),
    url(r'^financial-ratio/$', FinancialRatioAPIView.as_view(), name='financial-ratio'),
    url(r'^quarter-finacial/$', QuarterFinancialAPIView.as_view(), name='quarter-finacial'),
    url(r'^daily-buysell/$', DailyBuySellAPIView.as_view(), name='daily-buysell'),
    url(r'^weekly-buysell/$', WeeklyBuySellAPIView.as_view(), name='weekly-buysell'),

    url(r'^kospi-weekly-buy/$', KospiWeeklyBuyAPIView.as_view(), name='kospi-weekly-buy'),
    url(r'^kosdaq-weekly-buy/$', KosdaqWeeklyBuyAPIView.as_view(), name='kosdaq-weekly-buy'),
    url(r'^kospi-weekly-sell/$', KospiWeeklySellAPIView.as_view(), name='kospi-weekly-sell'),
    url(r'^kosdaq-weekly-sell/$', KosdaqWeeklySellAPIView.as_view(), name='kosdaq-weekly-sell'),
    url(r'^kospi-weekly-net/$', KospiWeeklyNetAPIView.as_view(), name='kospi-weekly-net'),
    url(r'^kosdaq-weekly-net/$', KosdaqWeeklyNetAPIView.as_view(), name='kosdaq-weekly-net'),
]
